# Generated by Django 6.0.5 on 2026-06-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_verified_alter_membership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='voter_invites_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
