# Generated by Django 6.0.5 on 2026-06-09 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
        ('users', '0001_initial'),
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='users.election'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='users.membership'),
        ),
        migrations.AddField(
            model_name='participant',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='users.election'),
        ),
        migrations.AddField(
            model_name='participant',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='users.membership'),
        ),
        migrations.AddField(
            model_name='participant',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='votes.votinglink'),
        ),
        migrations.AddField(
            model_name='position',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='users.election'),
        ),
        migrations.AddField(
            model_name='position',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='users.organisation'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.position'),
        ),
    ]
